// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    benchmark_summary: {
        name: "benchmark_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          tier: string;
          /** @sqlType DECIMAL(2,2) */
          hit_at_4: number;
          /** @sqlType DECIMAL(2,2) */
          mrr: number;
          /** @sqlType INT */
          avg_latency_ms: number;
        }>;
      };
    eval_queries: {
        name: "eval_queries";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          query: string;
          /** @sqlType STRING */
          language: string;
          /** @sqlType ARRAY<STRING> */
          expected_service_ids: unknown[];
          /** @sqlType STRING */
          tier: string;
        }>;
      };
    keyword_search: {
        name: "keyword_search";
        parameters: {
          /** STRING - use sql.string() */
          query: SQLStringMarker;
          /** any - use sql.*() */
          limit: SQLTypeMarker;
        };
        result: Array<{
          /** Primary key */
          service_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType STRING */
          description: string;
          /** Concatenated name + category + description for keyword search */
          searchable_text: string;
        }>;
      };
    services_enriched: {
        name: "services_enriched";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          service_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType STRING */
          icon: string;
          /** @sqlType STRING */
          description: string;
          /** Intent-rich description for embeddings */
          semantic_description: string;
          /** @sqlType ARRAY<STRING> */
          intent_tags: unknown[];
          /** @sqlType ARRAY<STRING> */
          user_intent_phrases: unknown[];
          /** @sqlType ARRAY<STRING> */
          synonyms: unknown[];
          /** @sqlType ARRAY<STRING> */
          target_segments: unknown[];
          /** Combined text for Vector Search index */
          embedding_text: string;
        }>;
      };
    services_raw: {
        name: "services_raw";
        parameters: Record<string, never>;
        result: Array<{
          /** Primary key */
          service_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType STRING */
          icon: string;
          /** @sqlType STRING */
          description: string;
          /** Concatenated name + category + description for keyword search */
          search_text: string;
        }>;
      };
  }
}
